/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormPemeriksaan;

import com.mysql.jdbc.PreparedStatement;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.EditorKit;
import javax.swing.text.html.HTMLEditorKit;
import Koneksi.Koneksi;
/**
 *
 * @author karno
 */
public class CetakDataPemeriksaan extends javax.swing.JFrame {

    public void Cetak(){
        String html = "<H4><center>Laporan Data Pemeriksaan Pasien Rumah Sakit Umum Taruna</center></h4>"+
                "<table width='98%' border='0' align='center' cellpadding='5' cellspacing='1'>"+
                    "<tr>"+
                        "<td bgcolor='#CCCCCC' align='center'><strong>Kode Pemeriksaan</Strong></td>"+
                        "<td bgcolor='#CCCCCC' align='center'><strong>Nama Pasien</Strong></td>"+
                        "<td bgcolor='#CCCCCC' align='center'><strong>Nama Dokter</Strong></td>"+
                        "<td bgcolor='#CCCCCC' align='center'><strong>Diagnosa</Strong></td>"+
                        "<td bgcolor='#CCCCCC' align='center'><strong>Tanggal Periksa</Strong></td>"+
                        "<td bgcolor='#CCCCCC' align='center'><strong>Tindakan</Strong></td>"+
                    "<tr>";
        
        try{
            String sql = "SELECT * FROM pemeriksaan "
                    + "INNER JOIN pasien ON pasien.id_pasien=pemeriksaan.id_pasien "
                    + "INNER JOIN dokter ON dokter.id_dokter=pemeriksaan.id_dokter";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                html = html + 
                    "<tr>" +
                        "<td bgcolor='#EEEEEE'>"+res.getString("kode_periksa")+"</td>"+
                        "<td bgcolor='#F8F8F8'>"+res.getString("nama_pasien")+"</td>"+
                        "<td bgcolor='#F8F8F8'>"+res.getString("nama_dokter")+"</td>"+
                        "<td bgcolor='#F8F8F8'>"+res.getString("diagnosa")+"</td>"+
                        "<td bgcolor='#F8F8F8'>"+res.getString("tgl_periksa")+"</td>"+
                        "<td bgcolor='#F8F8F8'>"+res.getString("tindakan")+"</td>"+
                    "</tr>";
            }
            
            EditorKit x = new HTMLEditorKit();
            tampilcetak.setEditorKit(x);
            tampilcetak.setText(html);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * Creates new form CetakDataPemeriksaan
     */
    public CetakDataPemeriksaan() {
        initComponents();
        Cetak();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btPrint = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampilcetak = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btPrint.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btPrint.setText("Cetak");
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, 30));

        btClose.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btClose.setText("Close");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        tampilcetak.setEditable(false);
        tampilcetak.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(tampilcetak);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 580, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        try{
            tampilcetak.print();
        } catch (PrinterException ex){
            //Logger.getLogger(CetakBuktiPembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CetakDataPemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CetakDataPemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CetakDataPemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CetakDataPemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CetakDataPemeriksaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btPrint;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane tampilcetak;
    // End of variables declaration//GEN-END:variables
}
