/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormPemeriksaan;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Koneksi.Koneksi;

/**
 *
 * @author karno
 */
public class DataPemeriksaan extends javax.swing.JInternalFrame {

    private void tampilkanData(){ 
        DefaultTableModel tableModel;
        tableModel = (DefaultTableModel)tblpemeriksaan.getModel();
        tableModel.getDataVector().removeAllElements();
        
        try{
            int no = 1;
            String sql = "SELECT * FROM pemeriksaan "
                    + "INNER JOIN pasien ON pasien.id_pasien=pemeriksaan.id_pasien "
                    + "INNER JOIN dokter ON dokter.id_dokter=pemeriksaan.id_dokter";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                tableModel.addRow(new Object[]{no++,res.getString(1),res.getString(8),res.getString(14),res.getString(4),res.getString(5), res.getString(6)});    
            }
            
        }catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    /**
     * Creates new form DataPemeriksaan
     */
    public DataPemeriksaan() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        tampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();
        btnformpemeriksaan = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        jScrollPane47 = new javax.swing.JScrollPane();
        tblpemeriksaan = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(820, 482));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Judul.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        Judul.setForeground(new java.awt.Color(31, 69, 113));
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("DATA PEMERIKSAAN");
        Judul.setAlignmentX(0.5F);
        jPanel2.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, -1));

        btnformpemeriksaan.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnformpemeriksaan.setText("Kelola Data Pemeriksaan");
        btnformpemeriksaan.setFocusable(false);
        btnformpemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnformpemeriksaanActionPerformed(evt);
            }
        });
        jPanel2.add(btnformpemeriksaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 180, 40));

        jButton21.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jButton21.setText(" Print");
        jButton21.setFocusable(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 110, 40));

        btnrefresh.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnrefresh.setText(" Refresh");
        btnrefresh.setFocusable(false);
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        jPanel2.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 110, 40));

        jScrollPane47.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tblpemeriksaan.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        tblpemeriksaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Pemeriksaan", "Nama Pasien", "Nama Dokter", "Diagnosa", "Tanggal Periksa"
            }
        ));
        tblpemeriksaan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane47.setViewportView(tblpemeriksaan);

        jPanel2.add(jScrollPane47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 740, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnformpemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnformpemeriksaanActionPerformed
        Pemeriksaan pemeriksaan = new Pemeriksaan();
        this.getDesktopPane().add(pemeriksaan);
        Dimension gs = this.getDesktopPane().getSize();
        Dimension cs = pemeriksaan.getSize();

        pemeriksaan.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        pemeriksaan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnformpemeriksaanActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        CetakDataPemeriksaan dataPemeriksaan = new CetakDataPemeriksaan();
        dataPemeriksaan.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        tampilkanData();
    }//GEN-LAST:event_btnrefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton btnformpemeriksaan;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton jButton21;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane47;
    private javax.swing.JTable tblpemeriksaan;
    // End of variables declaration//GEN-END:variables
}
