/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormPasien;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import Koneksi.Koneksi;
import FormPasien.CetakDataPasien;
/**
 *
 * @author karno
 */
public class DataPasien extends javax.swing.JInternalFrame {

    private void tampilkanData(){ 
        DefaultTableModel tableModel;
        tableModel = (DefaultTableModel)tblpasien.getModel();
        tableModel.getDataVector().removeAllElements();
        
        try{
            int no = 1;
            String sql = "SELECT * FROM pasien";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                tableModel.addRow(new Object[]{no++, res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6)});    
            }
            
        }catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    /**
     * Creates new form DataPasien
     */
    public DataPasien() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        tampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton29 = new javax.swing.JButton();
        btnFormPasien = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jScrollPane49 = new javax.swing.JScrollPane();
        tblpasien = new javax.swing.JTable();
        Judul = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(820, 483));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton29.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jButton29.setText(" Print");
        jButton29.setFocusable(false);
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 90, 40));

        btnFormPasien.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnFormPasien.setText("Kelola Data Pasien");
        btnFormPasien.setFocusable(false);
        btnFormPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormPasienActionPerformed(evt);
            }
        });
        jPanel1.add(btnFormPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 160, 40));

        jButton30.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jButton30.setText(" Refresh");
        jButton30.setFocusable(false);
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 90, 40));

        jScrollPane49.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tblpasien.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        tblpasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID Pasien", "Nama Pasien", "Jenis Kelamin", "Umur", "Alamat", "No HP"
            }
        ));
        tblpasien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane49.setViewportView(tblpasien);

        jPanel1.add(jScrollPane49, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 740, 290));

        Judul.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        Judul.setForeground(new java.awt.Color(31, 69, 113));
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("DATA PASIEN");
        Judul.setAlignmentX(0.5F);
        jPanel1.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        CetakDataPasien dataPasien = new CetakDataPasien();
        dataPasien.setVisible(true);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void btnFormPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormPasienActionPerformed
        Pasien pasien = new Pasien();
        this.getDesktopPane().add(pasien);
        Dimension gs = this.getDesktopPane().getSize();
        Dimension cs = pasien.getSize();

        pasien.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        pasien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFormPasienActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        tampilkanData();
    }//GEN-LAST:event_jButton30ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton btnFormPasien;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane49;
    private javax.swing.JTable tblpasien;
    // End of variables declaration//GEN-END:variables
}
