/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormSpesialis;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import Koneksi.Koneksi;
import FormSpesialis.CetakDataSpesialis;
/**
 *
 * @author karno
 */
public class DataSpesialis extends javax.swing.JInternalFrame {

    private void tampilkan_data(){ 
        DefaultTableModel tableModel;
        tableModel = (DefaultTableModel)tblspesialis.getModel();
        tableModel.getDataVector().removeAllElements();
        
        try{
            int no = 1;
            String sql = "SELECT * FROM spesialis";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                tableModel.addRow(new Object[]{no++,res.getString(1),res.getString(2)});    
            }
            
        }catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    public DataSpesialis() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        tampilkan_data();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane50 = new javax.swing.JScrollPane();
        tblspesialis = new javax.swing.JTable();
        jButton37 = new javax.swing.JButton();
        btnFormSpesialis = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        Judul = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(820, 483));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane50.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tblspesialis.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        tblspesialis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Kode Spesialis", "Nama Spesialis"
            }
        ));
        tblspesialis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane50.setViewportView(tblspesialis);

        jPanel1.add(jScrollPane50, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 740, 290));

        jButton37.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jButton37.setText(" Print");
        jButton37.setFocusable(false);
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 90, 40));

        btnFormSpesialis.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnFormSpesialis.setText("Kelola Data Spesialis");
        btnFormSpesialis.setFocusable(false);
        btnFormSpesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormSpesialisActionPerformed(evt);
            }
        });
        jPanel1.add(btnFormSpesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 150, 40));

        btnrefresh.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnrefresh.setText(" Refresh");
        btnrefresh.setFocusable(false);
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 90, 40));

        Judul.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        Judul.setForeground(new java.awt.Color(31, 69, 113));
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("INPUT DATA SPESIALIS");
        Judul.setAlignmentX(0.5F);
        jPanel1.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        CetakDataSpesialis dataSpesialis = new CetakDataSpesialis();
        dataSpesialis.setVisible(true);
    }//GEN-LAST:event_jButton37ActionPerformed

    private void btnFormSpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormSpesialisActionPerformed
        Spesialis spesialis = new Spesialis();
        this.getDesktopPane().add(spesialis);
        Dimension gs = this.getDesktopPane().getSize();
        Dimension cs = spesialis.getSize();

        spesialis.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        spesialis.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFormSpesialisActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        tampilkan_data();
    }//GEN-LAST:event_btnrefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton btnFormSpesialis;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton jButton37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane50;
    private javax.swing.JTable tblspesialis;
    // End of variables declaration//GEN-END:variables
}
