/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormObat;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import Koneksi.Koneksi;
import FormObat.CetakDataObat;
/**
 *
 * @author karno
 */
public class DataObat extends javax.swing.JInternalFrame {

    private void tampilkanData(){ 
        DefaultTableModel tableModel;
        tableModel = (DefaultTableModel)tblobat.getModel();
        tableModel.getDataVector().removeAllElements();
        
        try{
            int no = 1;
            String sql = "SELECT * FROM obat";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                tableModel.addRow(new Object[]{no++, res.getString(1), res.getString(2), res.getString(3), res.getString(4)});    
            }
            
        }catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    /**
     * Creates new form DataObat
     */
    public DataObat() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        tampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();
        jScrollPane51 = new javax.swing.JScrollPane();
        tblobat = new javax.swing.JTable();
        btnrefresh = new javax.swing.JButton();
        btnFormObat = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(820, 483));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Judul.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        Judul.setForeground(new java.awt.Color(31, 69, 113));
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("DATA OBAT");
        Judul.setAlignmentX(0.5F);
        jPanel1.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, -1));

        jScrollPane51.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tblobat.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        tblobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Obat", "Nama Obat", "Jenis Obat", "Harga"
            }
        ));
        tblobat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane51.setViewportView(tblobat);

        jPanel1.add(jScrollPane51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 740, 285));

        btnrefresh.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnrefresh.setText(" Refresh");
        btnrefresh.setFocusable(false);
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 90, 40));

        btnFormObat.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnFormObat.setText("Kelola Data Obat");
        btnFormObat.setFocusable(false);
        btnFormObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormObatActionPerformed(evt);
            }
        });
        jPanel1.add(btnFormObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 140, 40));

        jButton39.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jButton39.setText(" Print");
        jButton39.setFocusable(false);
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        tampilkanData();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnFormObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormObatActionPerformed
        Obat obat = new Obat();
        this.getDesktopPane().add(obat);
        Dimension gs = this.getDesktopPane().getSize();
        Dimension cs = obat.getSize();

        obat.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        obat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFormObatActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        CetakDataObat dataObat = new CetakDataObat();
        dataObat.setVisible(true);
    }//GEN-LAST:event_jButton39ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton btnFormObat;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton jButton39;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane51;
    private javax.swing.JTable tblobat;
    // End of variables declaration//GEN-END:variables
}
