/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormUtama;

/**
 *
 * @author karno
 */
public class Dashboard extends javax.swing.JInternalFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDashboard = new javax.swing.JPanel();
        gD1 = new javax.swing.JLabel();
        aD1 = new javax.swing.JLabel();
        tD1 = new javax.swing.JLabel();
        kD1 = new javax.swing.JLabel();
        tD2 = new javax.swing.JLabel();
        aD2 = new javax.swing.JLabel();
        gD2 = new javax.swing.JLabel();
        kD2 = new javax.swing.JLabel();
        gD3 = new javax.swing.JLabel();
        tD3 = new javax.swing.JLabel();
        aD3 = new javax.swing.JLabel();
        kD3 = new javax.swing.JLabel();
        judulGrafik = new javax.swing.JLabel();
        grafik = new javax.swing.JLabel();
        Judul = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        panelDashboard.setBackground(new java.awt.Color(255, 255, 255));
        panelDashboard.setMinimumSize(new java.awt.Dimension(820, 481));
        panelDashboard.setPreferredSize(new java.awt.Dimension(820, 481));
        panelDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/isikotak1.png"))); // NOI18N
        panelDashboard.add(gD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 50));

        aD1.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        aD1.setText("39");
        panelDashboard.add(aD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 20));

        tD1.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        tD1.setText("Pasien Per Hari");
        panelDashboard.add(tD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        kD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Kotak.png"))); // NOI18N
        panelDashboard.add(kD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        tD2.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        tD2.setText("Pasien Per Bulan");
        panelDashboard.add(tD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        aD2.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        aD2.setText("532");
        panelDashboard.add(aD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, 20));

        gD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/isikotak2.png"))); // NOI18N
        panelDashboard.add(gD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 40, 50));

        kD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Kotak.png"))); // NOI18N
        panelDashboard.add(kD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        gD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/isikotak3.png"))); // NOI18N
        panelDashboard.add(gD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 70, -1, 50));

        tD3.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        tD3.setText("Pasien Per Bulan");
        panelDashboard.add(tD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, -1));

        aD3.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        aD3.setText("120,475");
        panelDashboard.add(aD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, 20));

        kD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Kotak.png"))); // NOI18N
        panelDashboard.add(kD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        judulGrafik.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        judulGrafik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulGrafik.setText("Pasien Per Bulan Klinik Ihsan Medika Tahun 2025");
        panelDashboard.add(judulGrafik, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 800, -1));

        grafik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Grafik.png"))); // NOI18N
        panelDashboard.add(grafik, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        Judul.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        Judul.setForeground(new java.awt.Color(31, 69, 113));
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("DASHBOARD");
        Judul.setAlignmentX(0.5F);
        panelDashboard.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel aD1;
    private javax.swing.JLabel aD2;
    private javax.swing.JLabel aD3;
    private javax.swing.JLabel gD1;
    private javax.swing.JLabel gD2;
    private javax.swing.JLabel gD3;
    private javax.swing.JLabel grafik;
    private javax.swing.JLabel judulGrafik;
    private javax.swing.JLabel kD1;
    private javax.swing.JLabel kD2;
    private javax.swing.JLabel kD3;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JLabel tD1;
    private javax.swing.JLabel tD2;
    private javax.swing.JLabel tD3;
    // End of variables declaration//GEN-END:variables
}
