/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormUtama;


import java.awt.Color;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Locale;
import FormPemeriksaan.Pemeriksaan;
import FormRawatJalan.RawatJalan;
import FormPembayaran.Pembayaran;
import FormPasien.Pasien;
import FormDokter.Dokter;
import FormObat.Obat;
import FormSpesialis.Spesialis;

/**
 *
 * @author karno
 */
public class HalamanUtama extends javax.swing.JFrame {
java.util.Date tglsekarang = new java.util.Date();
    private final SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd/MM/yyyy", Locale.getDefault());
    //diatas adalah pengaturan format penulisan, bisa diubah sesuai keinginan.
    private final String tanggal = smpdtfmt.format(tglsekarang);
    
    public HalamanUtama() {
        initComponents();
        txttanggal.setText(tanggal);
        gDashboard.setVisible(true);
        gObat.setVisible(false);
        gDokter.setVisible(false);
        gPasien.setVisible(false);
        gPemeriksaan.setVisible(false);
        gPembayaran.setVisible(false);
        gRawatJalan.setVisible(false);
        gSpesialis.setVisible(false);
    }
    /**
     * Creates new form HalamanUtama
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        panelSidebar = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        gDashboard = new javax.swing.JLabel();
        btnPemeriksaan = new javax.swing.JButton();
        gPemeriksaan = new javax.swing.JLabel();
        btnRawatJalan = new javax.swing.JButton();
        gRawatJalan = new javax.swing.JLabel();
        btnPembayaran = new javax.swing.JButton();
        gPembayaran = new javax.swing.JLabel();
        btnPasien = new javax.swing.JButton();
        gPasien = new javax.swing.JLabel();
        btnDokter = new javax.swing.JButton();
        gDokter = new javax.swing.JLabel();
        btnObat = new javax.swing.JButton();
        gObat = new javax.swing.JLabel();
        btnSpesialis = new javax.swing.JButton();
        gSpesialis = new javax.swing.JLabel();
        garis = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        txttanggal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSidebar.setBackground(new java.awt.Color(255, 255, 255));
        panelSidebar.setRequestFocusEnabled(false);
        panelSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard.setBackground(new java.awt.Color(255, 255, 255));
        btnDashboard.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(31, 69, 113));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Dashboard.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setAutoscrolls(true);
        btnDashboard.setBorder(null);
        btnDashboard.setBorderPainted(false);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setDefaultCapable(false);
        btnDashboard.setFocusPainted(false);
        btnDashboard.setFocusable(false);
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard.setIconTextGap(9);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        panelSidebar.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 40));

        gDashboard.setBackground(new java.awt.Color(255, 255, 255));
        gDashboard.setForeground(new java.awt.Color(0, 153, 255));
        gDashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 69, 113), 2));
        gDashboard.setOpaque(true);
        panelSidebar.add(gDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, 40));

        btnPemeriksaan.setBackground(new java.awt.Color(255, 255, 255));
        btnPemeriksaan.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        btnPemeriksaan.setForeground(new java.awt.Color(31, 69, 113));
        btnPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Pemeriksaan.png"))); // NOI18N
        btnPemeriksaan.setText("Pemeriksaan");
        btnPemeriksaan.setAutoscrolls(true);
        btnPemeriksaan.setBorder(null);
        btnPemeriksaan.setBorderPainted(false);
        btnPemeriksaan.setContentAreaFilled(false);
        btnPemeriksaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPemeriksaan.setDefaultCapable(false);
        btnPemeriksaan.setFocusPainted(false);
        btnPemeriksaan.setFocusable(false);
        btnPemeriksaan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPemeriksaan.setIconTextGap(9);
        btnPemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemeriksaanActionPerformed(evt);
            }
        });
        panelSidebar.add(btnPemeriksaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, 40));

        gPemeriksaan.setBackground(new java.awt.Color(255, 255, 255));
        gPemeriksaan.setForeground(new java.awt.Color(0, 153, 255));
        gPemeriksaan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 69, 113), 2));
        gPemeriksaan.setOpaque(true);
        panelSidebar.add(gPemeriksaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 40));

        btnRawatJalan.setBackground(new java.awt.Color(255, 255, 255));
        btnRawatJalan.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        btnRawatJalan.setForeground(new java.awt.Color(31, 69, 113));
        btnRawatJalan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Rawat Jalan.png"))); // NOI18N
        btnRawatJalan.setText("Rawat Jalan");
        btnRawatJalan.setAutoscrolls(true);
        btnRawatJalan.setBorder(null);
        btnRawatJalan.setBorderPainted(false);
        btnRawatJalan.setContentAreaFilled(false);
        btnRawatJalan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRawatJalan.setDefaultCapable(false);
        btnRawatJalan.setFocusPainted(false);
        btnRawatJalan.setFocusable(false);
        btnRawatJalan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRawatJalan.setIconTextGap(9);
        btnRawatJalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRawatJalanActionPerformed(evt);
            }
        });
        panelSidebar.add(btnRawatJalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, 40));

        gRawatJalan.setBackground(new java.awt.Color(255, 255, 255));
        gRawatJalan.setForeground(new java.awt.Color(0, 153, 255));
        gRawatJalan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 69, 113), 2));
        gRawatJalan.setOpaque(true);
        panelSidebar.add(gRawatJalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 150, 40));

        btnPembayaran.setBackground(new java.awt.Color(255, 255, 255));
        btnPembayaran.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        btnPembayaran.setForeground(new java.awt.Color(31, 69, 113));
        btnPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Pembayaran.png"))); // NOI18N
        btnPembayaran.setText("Pembayaran");
        btnPembayaran.setAutoscrolls(true);
        btnPembayaran.setBorder(null);
        btnPembayaran.setBorderPainted(false);
        btnPembayaran.setContentAreaFilled(false);
        btnPembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPembayaran.setDefaultCapable(false);
        btnPembayaran.setFocusPainted(false);
        btnPembayaran.setFocusable(false);
        btnPembayaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPembayaran.setIconTextGap(9);
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });
        panelSidebar.add(btnPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 140, 40));

        gPembayaran.setBackground(new java.awt.Color(255, 255, 255));
        gPembayaran.setForeground(new java.awt.Color(0, 153, 255));
        gPembayaran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 69, 113), 2));
        gPembayaran.setOpaque(true);
        panelSidebar.add(gPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 150, 40));

        btnPasien.setBackground(new java.awt.Color(255, 255, 255));
        btnPasien.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        btnPasien.setForeground(new java.awt.Color(31, 69, 113));
        btnPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Pasien.png"))); // NOI18N
        btnPasien.setText("Pasien");
        btnPasien.setAutoscrolls(true);
        btnPasien.setBorder(null);
        btnPasien.setBorderPainted(false);
        btnPasien.setContentAreaFilled(false);
        btnPasien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPasien.setDefaultCapable(false);
        btnPasien.setFocusPainted(false);
        btnPasien.setFocusable(false);
        btnPasien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPasien.setIconTextGap(9);
        btnPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasienActionPerformed(evt);
            }
        });
        panelSidebar.add(btnPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 40));

        gPasien.setBackground(new java.awt.Color(255, 255, 255));
        gPasien.setForeground(new java.awt.Color(0, 153, 255));
        gPasien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 69, 113), 2));
        gPasien.setOpaque(true);
        panelSidebar.add(gPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 150, 40));

        btnDokter.setBackground(new java.awt.Color(255, 255, 255));
        btnDokter.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        btnDokter.setForeground(new java.awt.Color(31, 69, 113));
        btnDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Dokter.png"))); // NOI18N
        btnDokter.setText("Dokter");
        btnDokter.setAutoscrolls(true);
        btnDokter.setBorder(null);
        btnDokter.setBorderPainted(false);
        btnDokter.setContentAreaFilled(false);
        btnDokter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDokter.setDefaultCapable(false);
        btnDokter.setFocusPainted(false);
        btnDokter.setFocusable(false);
        btnDokter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDokter.setIconTextGap(9);
        btnDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDokterActionPerformed(evt);
            }
        });
        panelSidebar.add(btnDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, 40));

        gDokter.setBackground(new java.awt.Color(255, 255, 255));
        gDokter.setForeground(new java.awt.Color(0, 153, 255));
        gDokter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 69, 113), 2));
        gDokter.setOpaque(true);
        panelSidebar.add(gDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 40));

        btnObat.setBackground(new java.awt.Color(255, 255, 255));
        btnObat.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        btnObat.setForeground(new java.awt.Color(31, 69, 113));
        btnObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Obat.png"))); // NOI18N
        btnObat.setText("Obat");
        btnObat.setAutoscrolls(true);
        btnObat.setBorder(null);
        btnObat.setBorderPainted(false);
        btnObat.setContentAreaFilled(false);
        btnObat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnObat.setDefaultCapable(false);
        btnObat.setFocusPainted(false);
        btnObat.setFocusable(false);
        btnObat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnObat.setIconTextGap(9);
        btnObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObatActionPerformed(evt);
            }
        });
        panelSidebar.add(btnObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 140, 40));

        gObat.setBackground(new java.awt.Color(255, 255, 255));
        gObat.setForeground(new java.awt.Color(0, 153, 255));
        gObat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 69, 113), 2));
        gObat.setOpaque(true);
        panelSidebar.add(gObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 150, 40));

        btnSpesialis.setBackground(new java.awt.Color(255, 255, 255));
        btnSpesialis.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        btnSpesialis.setForeground(new java.awt.Color(31, 69, 113));
        btnSpesialis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Dokter.png"))); // NOI18N
        btnSpesialis.setText("Spesialis");
        btnSpesialis.setAutoscrolls(true);
        btnSpesialis.setBorder(null);
        btnSpesialis.setBorderPainted(false);
        btnSpesialis.setContentAreaFilled(false);
        btnSpesialis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSpesialis.setDefaultCapable(false);
        btnSpesialis.setFocusPainted(false);
        btnSpesialis.setFocusable(false);
        btnSpesialis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSpesialis.setIconTextGap(9);
        btnSpesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpesialisActionPerformed(evt);
            }
        });
        panelSidebar.add(btnSpesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 140, 40));

        gSpesialis.setBackground(new java.awt.Color(255, 255, 255));
        gSpesialis.setForeground(new java.awt.Color(0, 153, 255));
        gSpesialis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 69, 113), 2));
        gSpesialis.setOpaque(true);
        panelSidebar.add(gSpesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 150, 40));

        garis.setBackground(new java.awt.Color(31, 69, 113));
        garis.setForeground(new java.awt.Color(0, 153, 255));
        garis.setText(" ");
        garis.setOpaque(true);
        panelSidebar.add(garis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 10, 463));

        panelHeader.setBackground(new java.awt.Color(31, 69, 113));
        panelHeader.setLayout(null);

        txttanggal.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        txttanggal.setForeground(new java.awt.Color(255, 255, 255));
        panelHeader.add(txttanggal);
        txttanggal.setBounds(700, 0, 100, 100);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jl. Pangeran Antasari No.33");
        panelHeader.add(jLabel2);
        jLabel2.setBounds(180, 70, 410, 22);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISTEM INFORMASI RAWAT JALAN");
        panelHeader.add(jLabel3);
        jLabel3.setBounds(180, 20, 410, 20);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("KLINIK IHSAN MEDIKA");
        panelHeader.add(jLabel4);
        jLabel4.setBounds(180, 40, 410, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Tanggal.png"))); // NOI18N
        panelHeader.add(jLabel6);
        jLabel6.setBounds(650, 0, 40, 100);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Icon RS.png"))); // NOI18N
        panelHeader.add(jLabel7);
        jLabel7.setBounds(30, 10, 100, 90);

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Close (1).png"))); // NOI18N
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        panelHeader.add(Close);
        Close.setBounds(910, 10, 30, 30);

        DesktopPane.setBackground(new java.awt.Color(255, 255, 255));
        DesktopPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        DesktopPane.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(DesktopPane))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DesktopPane)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRawatJalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRawatJalanActionPerformed
        gDashboard.setVisible(false);
        gObat.setVisible(false);
        gDokter.setVisible(false);
        gPasien.setVisible(false);
        gPemeriksaan.setVisible(false);
        gPembayaran.setVisible(false);
        gRawatJalan.setVisible(true);
        gSpesialis.setVisible(false);

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();

        RawatJalan rawatJalan = new RawatJalan();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = rawatJalan.getSize();

        rawatJalan.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        rawatJalan.setVisible(true);

        //add panel
        DesktopPane.add(rawatJalan);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnRawatJalanActionPerformed

    private void btnObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObatActionPerformed
        gDashboard.setVisible(false);
        gObat.setVisible(true);
        gDokter.setVisible(false);
        gPasien.setVisible(false);
        gPemeriksaan.setVisible(false);
        gPembayaran.setVisible(false);
        gRawatJalan.setVisible(false);
        gSpesialis.setVisible(false);

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();

        Obat dataObat = new Obat();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = dataObat.getSize();

        dataObat.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        dataObat.setVisible(true);

        //add panel
        DesktopPane.add(dataObat);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnObatActionPerformed

    private void btnDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokterActionPerformed
        gDashboard.setVisible(false);
        gObat.setVisible(false);
        gDokter.setVisible(true);
        gPasien.setVisible(false);
        gPemeriksaan.setVisible(false);
        gPembayaran.setVisible(false);
        gRawatJalan.setVisible(false);
        gSpesialis.setVisible(false);

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();

        Dokter dataDokter = new Dokter();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = dataDokter.getSize();

        dataDokter.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        dataDokter.setVisible(true);

        //add panel
        DesktopPane.add(dataDokter);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnDokterActionPerformed

    private void btnPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasienActionPerformed
        gDashboard.setVisible(false);
        gObat.setVisible(false);
        gDokter.setVisible(false);
        gPasien.setVisible(true);
        gPemeriksaan.setVisible(false);
        gPembayaran.setVisible(false);
        gRawatJalan.setVisible(false);
        gSpesialis.setVisible(false);

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();

        Pasien dataPasien = new Pasien();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = dataPasien.getSize();

        dataPasien.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        dataPasien.setVisible(true);

        //add panel
        DesktopPane.add(dataPasien);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnPasienActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        gDashboard.setVisible(false);
        gObat.setVisible(false);
        gDokter.setVisible(false);
        gPasien.setVisible(false);
        gPemeriksaan.setVisible(false);
        gPembayaran.setVisible(true);
        gRawatJalan.setVisible(false);
        gSpesialis.setVisible(false);

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();

        Pembayaran pembayaran = new Pembayaran();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = pembayaran.getSize();

        pembayaran.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        pembayaran.setVisible(true);

        //add panel
        DesktopPane.add(pembayaran);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void btnPemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemeriksaanActionPerformed
        gDashboard.setVisible(false);
        gObat.setVisible(false);
        gDokter.setVisible(false);
        gPasien.setVisible(false);
        gPemeriksaan.setVisible(true);
        gPembayaran.setVisible(false);
        gRawatJalan.setVisible(false);
        gSpesialis.setVisible(false);

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();

        Pemeriksaan pemeriksaan = new Pemeriksaan();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = pemeriksaan.getSize();

        pemeriksaan.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        pemeriksaan.setVisible(true);

        //add panel
        DesktopPane.add(pemeriksaan);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnPemeriksaanActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        gDashboard.setVisible(true);
        gObat.setVisible(false);
        gDokter.setVisible(false);
        gPasien.setVisible(false);
        gPemeriksaan.setVisible(false);
        gPembayaran.setVisible(false);
        gRawatJalan.setVisible(false);
        gSpesialis.setVisible(false);

        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();

        Dashboard dashboard = new Dashboard();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = dashboard.getSize();

        dashboard.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        dashboard.setVisible(true);

        //add panel
        DesktopPane.add(dashboard);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CloseMouseClicked

    private void btnSpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpesialisActionPerformed
        gDashboard.setVisible(false);
        gObat.setVisible(false);
        gDokter.setVisible(false);
        gPasien.setVisible(false);
        gPemeriksaan.setVisible(false);
        gPembayaran.setVisible(false);
        gRawatJalan.setVisible(false);
        gSpesialis.setVisible(true);
        
        //remove panel
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.revalidate();
        
        Spesialis dataSpesialis = new Spesialis();
        Dimension gs = DesktopPane.getSize();
        Dimension cs = dataSpesialis.getSize();

        dataSpesialis.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        dataSpesialis.setVisible(true);

        //add panel
        DesktopPane.add(dataSpesialis);
        DesktopPane.repaint();
        DesktopPane.revalidate();
    }//GEN-LAST:event_btnSpesialisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    public static final javax.swing.JDesktopPane DesktopPane = new javax.swing.JDesktopPane();
    public javax.swing.JButton btnDashboard;
    public javax.swing.JButton btnDokter;
    public javax.swing.JButton btnObat;
    public javax.swing.JButton btnPasien;
    public javax.swing.JButton btnPembayaran;
    public javax.swing.JButton btnPemeriksaan;
    public javax.swing.JButton btnRawatJalan;
    public javax.swing.JButton btnSpesialis;
    public javax.swing.JLabel gDashboard;
    public javax.swing.JLabel gDokter;
    public javax.swing.JLabel gObat;
    public javax.swing.JLabel gPasien;
    public javax.swing.JLabel gPembayaran;
    public javax.swing.JLabel gPemeriksaan;
    public javax.swing.JLabel gRawatJalan;
    public javax.swing.JLabel gSpesialis;
    public javax.swing.JLabel garis;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JLabel txttanggal;
    // End of variables declaration//GEN-END:variables
}
