/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormUtama;

import javax.swing.ImageIcon;
/**
 *
 * @author karno
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtLoading = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        LoadingProgresBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 389));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLoading.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtLoading.setText("99 %");
        jPanel1.add(txtLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Aset Klinik Login 1 fix.png"))); // NOI18N
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 204));

        lblWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/header fix.png"))); // NOI18N
        jPanel1.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 137));

        LoadingProgresBar.setForeground(new java.awt.Color(25, 131, 237));
        LoadingProgresBar.setBorderPainted(false);
        LoadingProgresBar.setOpaque(true);
        jPanel1.add(LoadingProgresBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 220, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SplashScreen Splash = new SplashScreen();
        Splash.setVisible(true);
        
        try{
            for (int i=0; i <=100; i++){
                Thread.sleep(40);
                Splash.txtLoading.setText(""+i+" %");
                Splash.LoadingProgresBar.setValue(i);
                if ( i == 100){
                    Login login = new Login();
                    Splash.setVisible(false);
                    login.setVisible(true);
                }
            }
        }catch(Exception e){
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private transient javax.swing.JProgressBar LoadingProgresBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel txtLoading;
    // End of variables declaration//GEN-END:variables
}
