/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormDokter;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import Koneksi.Koneksi;
import FormDokter.CetakDataDokter;
/**
 *
 * @author karno
 */
public class DataDokter extends javax.swing.JInternalFrame {

    private void tampilkan_data(){ 
        DefaultTableModel tableModel;
        tableModel = (DefaultTableModel)tbldokter.getModel();
        tableModel.getDataVector().removeAllElements();
        
        try{
            int no = 1;
            String sql = "SELECT * FROM dokter "
                    + "INNER JOIN spesialis ON dokter.id_spesialis=spesialis.id_spesialis";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                tableModel.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(7),res.getString(4),res.getString(5)});    
            }
            
        }catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    /**
     * Creates new form DataDokter
     */
    public DataDokter() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        tampilkan_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane46 = new javax.swing.JScrollPane();
        tbldokter = new javax.swing.JTable();
        jButton19 = new javax.swing.JButton();
        btnFormDokter = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        Judul = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(820, 483));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane46.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tbldokter.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        tbldokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID Dokter", "Nama Dokter", "Spesialis", "Hari Praktek", "Jam Praktek"
            }
        ));
        tbldokter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane46.setViewportView(tbldokter);

        jPanel1.add(jScrollPane46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 740, 285));

        jButton19.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jButton19.setText(" Print");
        jButton19.setFocusable(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 90, 40));

        btnFormDokter.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnFormDokter.setText("Kelola Data Dokter");
        btnFormDokter.setFocusable(false);
        btnFormDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormDokterActionPerformed(evt);
            }
        });
        jPanel1.add(btnFormDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 160, 40));

        btnrefresh.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnrefresh.setText(" Refresh");
        btnrefresh.setFocusable(false);
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 90, 40));

        Judul.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        Judul.setForeground(new java.awt.Color(31, 69, 113));
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("DATA DOKTER");
        Judul.setAlignmentX(0.5F);
        jPanel1.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        CetakDataDokter dataDokter = new CetakDataDokter();
        dataDokter.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void btnFormDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormDokterActionPerformed
        Dokter dokter = new Dokter();
        this.getDesktopPane().add(dokter);
        Dimension gs = this.getDesktopPane().getSize();
        Dimension cs = dokter.getSize();

        dokter.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        dokter.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFormDokterActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        tampilkan_data();
    }//GEN-LAST:event_btnrefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton btnFormDokter;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton jButton19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane46;
    private javax.swing.JTable tbldokter;
    // End of variables declaration//GEN-END:variables
}
