/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormDokter;

import java.awt.Dimension;
import java.awt.HeadlessException;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.SQLException;
import static javafx.beans.binding.Bindings.or;
import javax.swing.JOptionPane;
import Koneksi.Koneksi;
import FormPemeriksaan.Pemeriksaan;
import java.util.ArrayList;
/**
 *
 * @author karno
 */
public class Dokter extends javax.swing.JInternalFrame {

       ArrayList idSpesialis = new ArrayList();
       
       private void reset(){
        txtid.setEditable(false);
        txtnama.setText(null);
        cbspesialis.setSelectedIndex(0);
        cbhari.setSelectedIndex(0);
        txtjam.setText(null);
        
        btnsimpan.setEnabled(true);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);

        kodeDokter();

    }
    
    private void tampilSpesialis(){
        try{
            String sql = "SELECT * FROM spesialis";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                cbspesialis.addItem(res.getString(2));
                idSpesialis.add(res.getString(1));
            }
            
        }catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    private void kodeDokter(){
        try{
            String sql = "SELECT MAX(right(id_dokter, 1)) AS id_dokter FROM dokter";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            if(res.next()){
                int kode = res.getInt(1);
                String AN = "" + (kode + 1);
                String Nol = "";
                
                if(AN.length() == 1){
                    Nol = "00";
                }else if(AN.length() == 2){
                    Nol = "0";
                }else if(AN.length() == 3){
                    Nol = "";
                }
                
                txtid.setText("DKT" + Nol + AN);
                
            } else {
                txtid.setText("DKT001");
            }
        } catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }
    /**
     * Creates new form Dokter
     */
    public Dokter() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        idSpesialis.add("0");
        tampilSpesialis();
        kodeDokter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btncari = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbspesialis = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtjam = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbhari = new javax.swing.JComboBox<>();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnDataDokter = new javax.swing.JButton();
        Judul = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(820, 483));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncari.setBackground(new java.awt.Color(255, 255, 255));
        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Cari.png"))); // NOI18N
        btncari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btncari.setBorderPainted(false);
        btncari.setContentAreaFilled(false);
        btncari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncari.setFocusable(false);
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        jPanel1.add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 40, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel13.setText("ID Dokter");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 60, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel14.setText("Nama");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        cbspesialis.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        cbspesialis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - Pilih Spesialis - -" }));
        cbspesialis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(cbspesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 220, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel17.setText("Spesialis");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel19.setText("Jadwal Praktik");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 30));

        txtjam.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtjam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 70, 30));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel20.setText("WIB");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, 30));

        cbhari.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        cbhari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - Pilih Hari - -", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));
        cbhari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbhari.setOpaque(false);
        jPanel1.add(cbhari, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 110, 30));

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(255, 255, 255));
        txtid.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtid.setText("Otomatis");
        txtid.setToolTipText("");
        txtid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 220, 30));

        txtnama.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtnama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 220, 30));

        btnsimpan.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Simpan.png"))); // NOI18N
        btnsimpan.setText(" Simpan");
        btnsimpan.setFocusable(false);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 110, 40));

        btnreset.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Reset.png"))); // NOI18N
        btnreset.setText(" Reset");
        btnreset.setFocusable(false);
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel1.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 110, 40));

        btndelete.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Delete.png"))); // NOI18N
        btndelete.setText(" Delete");
        btndelete.setEnabled(false);
        btndelete.setFocusable(false);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 110, 40));

        btnupdate.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Update.png"))); // NOI18N
        btnupdate.setText(" Update");
        btnupdate.setEnabled(false);
        btnupdate.setFocusable(false);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 110, 40));

        btnDataDokter.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnDataDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Data.png"))); // NOI18N
        btnDataDokter.setText("Data Dokter");
        btnDataDokter.setFocusable(false);
        btnDataDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataDokterActionPerformed(evt);
            }
        });
        jPanel1.add(btnDataDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 230, 40));

        Judul.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        Judul.setForeground(new java.awt.Color(31, 69, 113));
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("INPUT DATA DOKTER");
        Judul.setAlignmentX(0.5F);
        jPanel1.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        String id = JOptionPane.showInputDialog(null, "Cari Berdasarkan ID Doktter!!!");
        try{
            String sql = "SELECT * FROM dokter WHERE id_dokter='"+id+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            if(res.next()){
                int id_spesialis = idSpesialis.indexOf(res.getString(3));

                JOptionPane.showMessageDialog(null, "Data ditemukan");
                txtid.setText(res.getString(1));
                txtnama.setText(res.getString(2));
                cbspesialis.setSelectedIndex(id_spesialis);
                cbhari.setSelectedItem(res.getString(4));
                txtjam.setText(res.getString(5));

                btnsimpan.setEnabled(false);
                btnupdate.setEnabled(true);
                btndelete.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
                reset();
            }
        } catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }

    }//GEN-LAST:event_btncariActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed

        if(txtnama.getText().equals("") || txtjam.getText().equals("") || cbspesialis.getSelectedIndex() ==  0 || cbhari.getSelectedIndex() ==  0){
            JOptionPane.showMessageDialog(null, "Form Tidak Boleh Ada Yang Kosong!!!");
        }else{
            try {

                String id_spesialis = (String) idSpesialis.get((int)cbspesialis.getSelectedIndex());

                String sql = "INSERT INTO dokter(id_dokter, nama_dokter, id_spesialis, hari_praktek, jam_praktek) "
                + "VALUES('"+txtid.getText()+"', '"+txtnama.getText()+"','"+id_spesialis+"','"+cbhari.getSelectedItem()+"','"+txtjam.getText()+"')";
                java.sql.Connection conn = (Connection)Koneksi.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Prosess Simpan Data Dokter Berhasil..");
                //            tampilkan_data();
                reset();
                kodeDokter();

            }catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        reset();
        kodeDokter();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed

        int tanya = JOptionPane.showConfirmDialog(null, "Yakin untuk menghapus data ini?","Confirmation", JOptionPane.YES_NO_OPTION);

        if(tanya==0){
            try{
                String sql = "DELETE FROM dokter WHERE id_dokter='"+txtid.getText()+"'";
                java.sql.Connection conn = (Connection)Koneksi.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Hapus Data Dokter Berhasil....");
            }catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            reset();
            kodeDokter();
        }

    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {

            String id_spesialis = (String) idSpesialis.get((int)cbspesialis.getSelectedIndex());

            String sql = "UPDATE dokter SET nama_dokter='"+txtnama.getText()+"', id_spesialis='"+id_spesialis+"', hari_praktek='"+cbhari.getSelectedItem()+"', jam_praktek='"+txtjam.getText()+"' WHERE id_dokter = '"+txtid.getText()+"'";
            java.sql.Connection conn = (Connection)Koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Dokter Berhasil...");
            kodeDokter();
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        reset();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnDataDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataDokterActionPerformed
        DataDokter dataDokter = new DataDokter();
        this.getDesktopPane().add(dataDokter);
        Dimension gs = this.getDesktopPane().getSize();
        Dimension cs = dataDokter.getSize();

        dataDokter.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        dataDokter.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDataDokterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton btnDataDokter;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbhari;
    private javax.swing.JComboBox<String> cbspesialis;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtjam;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
