/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormPembayaran;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import Koneksi.Koneksi;

/**
 *
 * @author karno
 */
public class DataPembayaran extends javax.swing.JInternalFrame {

    String rawat;
    String kodePeriksa;

    private void tampilkanData(){ 
        DefaultTableModel tableModel;
        tableModel = (DefaultTableModel)tblpembayaran.getModel();
        tableModel.getDataVector().removeAllElements();
        
        try{
            int no = 1;
            String sql = "SELECT * FROM pembayaran "
                    + "INNER JOIN pemeriksaan ON pemeriksaan.kode_periksa=pembayaran.kode_periksa "
                    + "INNER JOIN pasien ON pasien.id_pasien=pemeriksaan.id_pasien "
                    + "INNER JOIN dokter ON dokter.id_dokter=pemeriksaan.id_dokter ";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                tableModel.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(13),res.getString(19), res.getString(3), res.getString(4), res.getString(5)});    
            }
            
        }catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    /**
     * Creates new form DataPembayaran
     */
    public DataPembayaran() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        tampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane47 = new javax.swing.JScrollPane();
        tblpembayaran = new javax.swing.JTable();
        btnrefresh = new javax.swing.JButton();
        btnformrawatjalan = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        Judul = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(820, 483));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane47.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tblpembayaran.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        tblpembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Pembayaran", "Kode Pemeriksaan", "Nama Pasien", "Nama Dokter", "Total Biaya", "Pembayaran", "Kembalian"
            }
        ));
        tblpembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane47.setViewportView(tblpembayaran);

        jPanel1.add(jScrollPane47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 740, 290));

        btnrefresh.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnrefresh.setText(" Refresh");
        btnrefresh.setFocusable(false);
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 110, 40));

        btnformrawatjalan.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnformrawatjalan.setText("Kelola Data Pembayaran");
        btnformrawatjalan.setFocusable(false);
        btnformrawatjalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnformrawatjalanActionPerformed(evt);
            }
        });
        jPanel1.add(btnformrawatjalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 180, 40));

        jButton21.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jButton21.setText(" Print");
        jButton21.setFocusable(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 110, 40));

        Judul.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        Judul.setForeground(new java.awt.Color(31, 69, 113));
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("DATA PEMBAYARAN");
        Judul.setAlignmentX(0.5F);
        jPanel1.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        tampilkanData();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnformrawatjalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnformrawatjalanActionPerformed
        Pembayaran pembayaran = new Pembayaran();
        this.getDesktopPane().add(pembayaran);
        Dimension gs = this.getDesktopPane().getSize();
        Dimension cs = pembayaran.getSize();

        pembayaran.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        pembayaran.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnformrawatjalanActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        CetakDataPembayaran dataPembayaran = new CetakDataPembayaran();
        dataPembayaran.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton btnformrawatjalan;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton jButton21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane47;
    private javax.swing.JTable tblpembayaran;
    // End of variables declaration//GEN-END:variables
}
