/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormPembayaran;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import Koneksi.Koneksi;

/**
 *
 * @author karno
 */
public class Pembayaran extends javax.swing.JInternalFrame {

    String rawat;
    String kodeperiksa;
    
    private void reset(){
        txtkodepembayaran.setEditable(false);
        txtkodeperiksa.setText(null);
        txtnamapasien.setText(null);
        txtnamadokter.setText(null);
        txttotal.setText(null);
        txtbayar.setText(null);
        txtkembalian.setText(null);
        
        btnsimpan.setEnabled(true);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        btncaripemeriksaan.setEnabled(true);

        kodeBayar();

    }
    
    private void kodeBayar(){
        try{
            String sql = "SELECT MAX(right(id, 1)) AS id FROM pembayaran";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            if(res.next()){
                int kode = res.getInt(1);
                String AN = "" + (kode + 1);
                String Nol = "";
                
                if(AN.length() == 1){
                    Nol = "00";
                }else if(AN.length() == 2){
                    Nol = "0";
                }else if(AN.length() == 3){
                    Nol = "";
                }
                
                txtkodepembayaran.setText("BYR" + Nol + AN);
                
            } else {
                txtkodepembayaran.setText("BYR001");
            }
        } catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }
    /**
     * Creates new form Pembayaran
     */
    public Pembayaran() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        kodeBayar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btncari = new javax.swing.JButton();
        btncaripemeriksaan = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtkodepembayaran = new javax.swing.JTextField();
        txtkodeperiksa = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnDataPembayaran = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        txtnamapasien = new javax.swing.JTextField();
        txtnamadokter = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtkembalian = new javax.swing.JTextField();
        Judul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(820, 483));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncari.setBackground(new java.awt.Color(255, 255, 255));
        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Cari.png"))); // NOI18N
        btncari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btncari.setBorderPainted(false);
        btncari.setContentAreaFilled(false);
        btncari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncari.setFocusable(false);
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        jPanel1.add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 40, 30));

        btncaripemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Cari.png"))); // NOI18N
        btncaripemeriksaan.setBorderPainted(false);
        btncaripemeriksaan.setContentAreaFilled(false);
        btncaripemeriksaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncaripemeriksaan.setFocusable(false);
        btncaripemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaripemeriksaanActionPerformed(evt);
            }
        });
        jPanel1.add(btncaripemeriksaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 40, 30));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel23.setText("Kode Pembayaran");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 30));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel28.setText("Kode Periksa");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        txtkodepembayaran.setEditable(false);
        txtkodepembayaran.setBackground(new java.awt.Color(255, 255, 255));
        txtkodepembayaran.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtkodepembayaran.setText("Otomatis");
        txtkodepembayaran.setToolTipText("");
        txtkodepembayaran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtkodepembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 218, 30));

        txtkodeperiksa.setEditable(false);
        txtkodeperiksa.setBackground(new java.awt.Color(255, 255, 255));
        txtkodeperiksa.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtkodeperiksa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtkodeperiksa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 218, 30));

        btnsimpan.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Simpan.png"))); // NOI18N
        btnsimpan.setText(" Simpan");
        btnsimpan.setFocusable(false);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 110, 40));

        btnupdate.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Update.png"))); // NOI18N
        btnupdate.setText(" Update");
        btnupdate.setEnabled(false);
        btnupdate.setFocusable(false);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 110, 40));

        btndelete.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Delete.png"))); // NOI18N
        btndelete.setText(" Delete");
        btndelete.setEnabled(false);
        btndelete.setFocusable(false);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 110, 40));

        btnreset.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Reset.png"))); // NOI18N
        btnreset.setText(" Reset");
        btnreset.setFocusable(false);
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel1.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 110, 40));

        btnDataPembayaran.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnDataPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Data.png"))); // NOI18N
        btnDataPembayaran.setText(" Data Pembayaran");
        btnDataPembayaran.setFocusable(false);
        btnDataPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataPembayaranActionPerformed(evt);
            }
        });
        jPanel1.add(btnDataPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 230, 40));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel35.setText("Nama Pasien");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        txtnamapasien.setEditable(false);
        txtnamapasien.setBackground(new java.awt.Color(255, 255, 255));
        txtnamapasien.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtnamapasien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtnamapasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamapasienActionPerformed(evt);
            }
        });
        jPanel1.add(txtnamapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 218, 30));

        txtnamadokter.setEditable(false);
        txtnamadokter.setBackground(new java.awt.Color(255, 255, 255));
        txtnamadokter.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtnamadokter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtnamadokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 218, 30));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel36.setText("Nama Dokter");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 30));

        txttotal.setEditable(false);
        txttotal.setBackground(new java.awt.Color(255, 255, 255));
        txttotal.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txttotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 180, 30));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel38.setText("Total Tagihan");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 30));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel39.setText("Pembayaran");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 30));

        txtbayar.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtbayar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbayarKeyReleased(evt);
            }
        });
        jPanel1.add(txtbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 180, 30));

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel40.setText("Kembalian");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 30));

        txtkembalian.setEditable(false);
        txtkembalian.setBackground(new java.awt.Color(255, 255, 255));
        txtkembalian.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtkembalian.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembalianActionPerformed(evt);
            }
        });
        jPanel1.add(txtkembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 180, 30));

        Judul.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        Judul.setForeground(new java.awt.Color(31, 69, 113));
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("INPUT DATA RAWAT PEMBAYARAN");
        Judul.setAlignmentX(0.5F);
        jPanel1.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, -1));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setText("Rp.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 33, 28));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel2.setText("Rp.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 33, 28));

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel3.setText("Rp.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 33, 28));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        String id = JOptionPane.showInputDialog(null, "Cari Berdasarkan Kode Pembayaran!!!");
        try{
            String sql = "SELECT * FROM pembayaran "
            + "INNER JOIN pemeriksaan ON pemeriksaan.kode_periksa=pembayaran.kode_periksa "
            + "INNER JOIN pasien ON pasien.id_pasien=pemeriksaan.id_pasien "
            + "INNER JOIN dokter ON dokter.id_dokter=pemeriksaan.id_dokter "
            + "WHERE id='"+id+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            if(res.next()){
                JOptionPane.showMessageDialog(null, "Data ditemukan");
                txtkodepembayaran.setText(res.getString(1));
                txtkodeperiksa.setText(res.getString(2));
                txtnamapasien.setText(res.getString(13));
                txtnamadokter.setText(res.getString(19));
                txttotal.setText(res.getString(3));
                txtbayar.setText(res.getString(4));
                txtkembalian.setText(res.getString(5));

                btnsimpan.setEnabled(false);
                btnupdate.setEnabled(true);
                btndelete.setEnabled(true);
                btncaripemeriksaan.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
                reset();
            }
        } catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }

    }//GEN-LAST:event_btncariActionPerformed

    private void btncaripemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaripemeriksaanActionPerformed
        String kode = JOptionPane.showInputDialog(null, "Cari Berdasarkan Kode Pemeriksaan!!!");
        try{
            String sql = "SELECT * FROM pemeriksaan "
            + "INNER JOIN pasien ON pasien.id_pasien=pemeriksaan.id_pasien "
            + "INNER JOIN dokter ON dokter.id_dokter=pemeriksaan.id_dokter "
            + "WHERE kode_periksa='"+kode+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            if(res.next()){
                JOptionPane.showMessageDialog(null, "Data ditemukan");
                txtkodeperiksa.setText(res.getString(1));
                txtnamapasien.setText(res.getString(8));
                txtnamadokter.setText(res.getString(14));

                rawat = res.getString(6);
                kodeperiksa = res.getString(1);

                if(rawat.equals("Rawat Jalan")){
                    try{
                        String sqlr = "SELECT * FROM rawat_jalan "
                        + "WHERE kode_periksa='"+kodeperiksa+"'";
                        java.sql.Connection connr=(Connection)Koneksi.configDB();
                        java.sql.Statement stmr = connr.createStatement();
                        java.sql.ResultSet resr = stmr.executeQuery(sqlr);

                        if(resr.next()){
                            txttotal.setText(resr.getString(5));
                        } else {
                            JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
                            reset();
                        }
                    } catch (Exception e){
                        System.out.print(e);
                        JOptionPane.showMessageDialog(null, "Koneksi Gagal");
                    }

                }else if(rawat.equals("Rawat Inap")){
                    try{
                        String sqlr = "SELECT * FROM rawat_inap "
                        + "WHERE kode_periksa='"+kodeperiksa+"'";
                        java.sql.Connection connr=(Connection)Koneksi.configDB();
                        java.sql.Statement stmr = connr.createStatement();
                        java.sql.ResultSet resr = stmr.executeQuery(sqlr);

                        if(resr.next()){
                            txttotal.setText(resr.getString(6));
                        } else {
                            JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
                            reset();
                        }
                    } catch (Exception e){
                        System.out.print(e);
                        JOptionPane.showMessageDialog(null, "Koneksi Gagal");
                    }

                }
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
                reset();
            }
        } catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_btncaripemeriksaanActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if(txtkodepembayaran.getText().equals("") || txtkodeperiksa.getText().equals("") || txtnamapasien.getText().equals("") || txtnamadokter.getText().equals("") || txtbayar.getText().equals("") || txttotal.getText().equals("") || txtkembalian.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Form Tidak Boleh Ada Yang Kosong!!!");
        }else{
            try {
                String sql = "INSERT INTO pembayaran(id, kode_periksa, harga, pembayaran, kembalian) "
                + "VALUES('"+txtkodepembayaran.getText()+"', '"+txtkodeperiksa.getText()+"', '"+txttotal.getText()+"', '"+txtbayar.getText()+"', '"+txtkembalian.getText()+"')";
                java.sql.Connection conn = (Connection)Koneksi.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Prosess Simpan Data Pembayaran Berhasil..");
                reset();
                kodeBayar();

            }catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {
            String sql = "UPDATE pembayaran SET kode_periksa='"+txtkodeperiksa.getText()+"', harga='"+txttotal.getText()+"', pembayaran='"+txtbayar.getText()+"', kembalian='"+txtkembalian.getText()+"' WHERE id = '"+txtkodepembayaran.getText()+"'";
            java.sql.Connection conn = (Connection)Koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Pembayaran Berhasil...");
            kodeBayar();
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        reset();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int tanya = JOptionPane.showConfirmDialog(null, "Yakin untuk menghapus data ini?","Confirmation", JOptionPane.YES_NO_OPTION);

        if(tanya==0){
            try{
                String sql = "DELETE FROM pembayaran WHERE id='"+txtkodepembayaran.getText()+"'";
                java.sql.Connection conn = (Connection)Koneksi.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Hapus Data Rawat Jalan Berhasil....");
            }catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            reset();
            kodeBayar();
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        reset();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnDataPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataPembayaranActionPerformed
        DataPembayaran dataPembayaran = new DataPembayaran();
        this.getDesktopPane().add(dataPembayaran);
        Dimension gs = this.getDesktopPane().getSize();
        Dimension cs = dataPembayaran.getSize();

        dataPembayaran.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        dataPembayaran.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDataPembayaranActionPerformed

    private void txtbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyReleased
        if(txtbayar.getText().equals("") || txtbayar.getText().equals("0")){
            JOptionPane.showMessageDialog(rootPane, "Nominal Bayar Tidak Boleh Kosong!!!");
            txtbayar.setText(txttotal.getText());
        }else {
            int harga = Integer.parseInt(txttotal.getText());
            int bayar = Integer.parseInt(txtbayar.getText());
            int kembalian = bayar - harga;
            txtkembalian.setText(String.valueOf(kembalian));
        }
    }//GEN-LAST:event_txtbayarKeyReleased

    private void txtnamapasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamapasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamapasienActionPerformed

    private void txtkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkembalianActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton btnDataPembayaran;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btncaripemeriksaan;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtkodepembayaran;
    private javax.swing.JTextField txtkodeperiksa;
    private javax.swing.JTextField txtnamadokter;
    private javax.swing.JTextField txtnamapasien;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
