/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormRawatJalan;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import Koneksi.Koneksi;
/**
 *
 * @author karno
 */
public class DataRawatJalan extends javax.swing.JInternalFrame {

    private void tampilkanData(){ 
        DefaultTableModel tableModel;
        tableModel = (DefaultTableModel)tblrawatjalan.getModel();
        tableModel.getDataVector().removeAllElements();
        
        try{
            int no = 1;
            String sql = "SELECT * FROM rawat_jalan "
                    + "INNER JOIN pemeriksaan ON pemeriksaan.kode_periksa=rawat_jalan.kode_periksa "
                    + "INNER JOIN pasien ON pasien.id_pasien=pemeriksaan.id_pasien "
                    + "INNER JOIN obat ON obat.kode_obat=rawat_jalan.kode_obat ";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                tableModel.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(13),res.getString(20),res.getString(19), res.getString(21), res.getString(4), res.getString(5)});    
            }
            
        }catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    /**
     * Creates new form DataRawatJalan
     */
    public DataRawatJalan() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        tampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDataRawatJalan = new javax.swing.JPanel();
        jScrollPane47 = new javax.swing.JScrollPane();
        tblrawatjalan = new javax.swing.JTable();
        jButton21 = new javax.swing.JButton();
        btnformrawatjalan = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        Judul = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        panelDataRawatJalan.setBackground(new java.awt.Color(255, 255, 255));
        panelDataRawatJalan.setMinimumSize(new java.awt.Dimension(754, 482));
        panelDataRawatJalan.setPreferredSize(new java.awt.Dimension(820, 482));
        panelDataRawatJalan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane47.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tblrawatjalan.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        tblrawatjalan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Rawat", "Kode Pemeriksaan", "Nama Pasien", "Tipe Obat", "Nama Obat", "Harga Obat", "Jumlah Obat", "Total Harga"
            }
        ));
        tblrawatjalan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane47.setViewportView(tblrawatjalan);

        panelDataRawatJalan.add(jScrollPane47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 740, 290));

        jButton21.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jButton21.setText(" Print");
        jButton21.setFocusable(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        panelDataRawatJalan.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 90, 40));

        btnformrawatjalan.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnformrawatjalan.setText("Kelola Data Rawat Jalan");
        btnformrawatjalan.setFocusable(false);
        btnformrawatjalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnformrawatjalanActionPerformed(evt);
            }
        });
        panelDataRawatJalan.add(btnformrawatjalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 180, 40));

        btnrefresh.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnrefresh.setText(" Refresh");
        btnrefresh.setFocusable(false);
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        panelDataRawatJalan.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 90, 40));

        Judul.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        Judul.setForeground(new java.awt.Color(31, 69, 113));
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("DATA RAWAT JALAN");
        Judul.setAlignmentX(0.5F);
        panelDataRawatJalan.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDataRawatJalan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDataRawatJalan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        CetakRawatJalan dataRawatJalan = new CetakRawatJalan();
        dataRawatJalan.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void btnformrawatjalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnformrawatjalanActionPerformed
        RawatJalan rawatJalan = new RawatJalan();
        this.getDesktopPane().add(rawatJalan);
        Dimension gs = this.getDesktopPane().getSize();
        Dimension cs = rawatJalan.getSize();

        rawatJalan.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        rawatJalan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnformrawatjalanActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        tampilkanData();
    }//GEN-LAST:event_btnrefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton btnformrawatjalan;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton jButton21;
    private javax.swing.JScrollPane jScrollPane47;
    private javax.swing.JPanel panelDataRawatJalan;
    private javax.swing.JTable tblrawatjalan;
    // End of variables declaration//GEN-END:variables
}
