/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormRawatJalan;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Koneksi.Koneksi;
/**
 *
 * @author karno
 */
public class RawatJalan extends javax.swing.JInternalFrame {

    ArrayList kodeObat = new ArrayList();
    
    private void reset(){
        txtkoderawat.setEditable(false);
        txtkodeperiksa.setText(null);
        txtnamapasien.setText(null);
        cbobat.setSelectedIndex(0);
        txtharga.setText(null);
        txtjmlobat.setText(null);
        txttotalharga.setText(null);
        
        
        btnsimpan.setEnabled(true);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        btncaripemeriksaan.setEnabled(true);
        
        kodeRawat();

    }
    
    private void tampilObat(){
        try{
            String sql = "SELECT * FROM obat";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                cbobat.addItem(res.getString(2));
                kodeObat.add(res.getString(1));
            }
            
        }catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    private void kodeRawat(){
        try{
            String sql = "SELECT MAX(right(id_rawat_jalan, 1)) AS id_rawat_jalan FROM rawat_jalan";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            if(res.next()){
                int kode = res.getInt(1);
                String AN = "" + (kode + 1);
                String Nol = "";
                
                if(AN.length() == 1){
                    Nol = "00";
                }else if(AN.length() == 2){
                    Nol = "0";
                }else if(AN.length() == 3){
                    Nol = "";
                }
                
                txtkoderawat.setText("RWJ" + Nol + AN);
                
            } else {
                txtkoderawat.setText("RWJ001");
            }
        } catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }
    /**
     * Creates new form RawatJalan
     */
    public RawatJalan() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        kodeObat.add("0");
        tampilObat();
        kodeRawat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();
        btncari = new javax.swing.JButton();
        btncaripemeriksaan = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtkoderawat = new javax.swing.JTextField();
        txtkodeperiksa = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtnamapasien = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbobat = new javax.swing.JComboBox<>();
        btnsimpan = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnDataRawatJalan = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txttotalharga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtjmlobat = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(820, 483));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Judul.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        Judul.setForeground(new java.awt.Color(31, 69, 113));
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("INPUT DATA RAWAT JALAN");
        Judul.setAlignmentX(0.5F);
        jPanel1.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, -1));

        btncari.setBackground(new java.awt.Color(255, 255, 255));
        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Cari.png"))); // NOI18N
        btncari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btncari.setBorderPainted(false);
        btncari.setContentAreaFilled(false);
        btncari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncari.setFocusable(false);
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        jPanel1.add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 40, 30));

        btncaripemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Cari.png"))); // NOI18N
        btncaripemeriksaan.setBorderPainted(false);
        btncaripemeriksaan.setContentAreaFilled(false);
        btncaripemeriksaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncaripemeriksaan.setFocusable(false);
        btncaripemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaripemeriksaanActionPerformed(evt);
            }
        });
        jPanel1.add(btncaripemeriksaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 40, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel15.setText("Kode Rawat Jalan");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel16.setText("Kode Pemeriksaan");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        txtkoderawat.setEditable(false);
        txtkoderawat.setBackground(new java.awt.Color(255, 255, 255));
        txtkoderawat.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtkoderawat.setText("Otomatis");
        txtkoderawat.setToolTipText("");
        txtkoderawat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtkoderawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 218, 30));

        txtkodeperiksa.setEditable(false);
        txtkodeperiksa.setBackground(new java.awt.Color(255, 255, 255));
        txtkodeperiksa.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtkodeperiksa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtkodeperiksa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 218, 30));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel24.setText("Nama Pasien");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        txtnamapasien.setEditable(false);
        txtnamapasien.setBackground(new java.awt.Color(255, 255, 255));
        txtnamapasien.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtnamapasien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtnamapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 218, 30));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel18.setText("Obat");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 30));

        cbobat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbobat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - Pilih Obat - -" }));
        cbobat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbobatActionPerformed(evt);
            }
        });
        jPanel1.add(cbobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 218, 30));

        btnsimpan.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Simpan.png"))); // NOI18N
        btnsimpan.setText(" Simpan");
        btnsimpan.setFocusable(false);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 110, 40));

        btnupdate.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Update.png"))); // NOI18N
        btnupdate.setText(" Update");
        btnupdate.setEnabled(false);
        btnupdate.setFocusable(false);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 110, 40));

        btndelete.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Delete.png"))); // NOI18N
        btndelete.setText(" Delete");
        btndelete.setEnabled(false);
        btndelete.setFocusable(false);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 110, 40));

        btnreset.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Reset.png"))); // NOI18N
        btnreset.setText(" Reset");
        btnreset.setFocusable(false);
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel1.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 110, 40));

        btnDataRawatJalan.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        btnDataRawatJalan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/Data.png"))); // NOI18N
        btnDataRawatJalan.setText(" Data Rawat Jalan");
        btnDataRawatJalan.setFocusable(false);
        btnDataRawatJalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataRawatJalanActionPerformed(evt);
            }
        });
        jPanel1.add(btnDataRawatJalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 230, 40));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel25.setText("Harga");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 30));

        txttotalharga.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txttotalharga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txttotalharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 190, 30));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setText("Rp.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 33, 28));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel27.setText("Jumlah Obat");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 30));

        txtjmlobat.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtjmlobat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtjmlobat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjmlobatKeyReleased(evt);
            }
        });
        jPanel1.add(txtjmlobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 220, 30));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel29.setText("Total Harga");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 30));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel2.setText("Rp.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 33, 28));

        txtharga.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtharga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        String kode = JOptionPane.showInputDialog(null, "Cari Berdasarkan Kode Rawat Jalan!!!");
        try{
            String sql = "SELECT * FROM rawat_jalan "
            + "INNER JOIN pemeriksaan ON pemeriksaan.kode_periksa=rawat_jalan.kode_periksa "
            + "INNER JOIN pasien ON pasien.id_pasien=pemeriksaan.id_pasien "
            + "INNER JOIN obat ON obat.kode_obat=rawat_jalan.kode_obat "
            + "WHERE id_rawat_jalan='"+kode+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            if(res.next()){
                JOptionPane.showMessageDialog(null, "Data ditemukan");
                txtkoderawat.setText(res.getString(1));
                txtkodeperiksa.setText(res.getString(2));
                txtnamapasien.setText(res.getString(14));
                cbobat.setSelectedItem(res.getString(19));
                txtharga.setText(res.getString(21));
                txtjmlobat.setText(res.getString(4));
                txttotalharga.setText(res.getString(5));

                btnsimpan.setEnabled(false);
                btnupdate.setEnabled(true);
                btndelete.setEnabled(true);
                btncaripemeriksaan.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
                reset();
            }
        } catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_btncariActionPerformed

    private void btncaripemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaripemeriksaanActionPerformed
        String kode = JOptionPane.showInputDialog(null, "Cari Berdasarkan Kode Pemeriksaan!!!");
        try{
            String sql = "SELECT * FROM pemeriksaan "
            + "INNER JOIN pasien ON pasien.id_pasien=pemeriksaan.id_pasien "
            + "WHERE kode_periksa='"+kode+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            if(res.next()){
                JOptionPane.showMessageDialog(null, "Data ditemukan");
                txtkodeperiksa.setText(res.getString(1));
                txtnamapasien.setText(res.getString(8));
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
                reset();
            }
        } catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_btncaripemeriksaanActionPerformed

    private void cbobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbobatActionPerformed
        try{

            String kode_obat = (String) kodeObat.get((int)cbobat.getSelectedIndex());

            String sql = "SELECT * FROM obat "
            + "WHERE kode_obat='"+kode_obat+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            if(res.next()){
                txtharga.setText(res.getString(4));
            }
        } catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_cbobatActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if(txtkoderawat.getText().equals("") || txtkodeperiksa.getText().equals("") || txtnamapasien.getText().equals("") || cbobat.getSelectedIndex() ==  0 || txtharga.getText().equals("") || txtjmlobat.getText().equals("") || txttotalharga.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Form Selain Tanggal Keluar dan Total Biaya Tidak Boleh Ada Yang Kosong!!!");
        }else{
            try {

                String kode_obat = (String) kodeObat.get((int)cbobat.getSelectedIndex());

                String sql = "INSERT INTO rawat_jalan(id_rawat_jalan, kode_periksa, kode_obat, jumlah_obat, harga) "
                + "VALUES('"+txtkoderawat.getText()+"', '"+txtkodeperiksa.getText()+"', '"+kode_obat+"', '"+txtjmlobat.getText()+"', '"+txttotalharga.getText()+"')";
                java.sql.Connection conn = (Connection)Koneksi.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Prosess Simpan Data Rawat Jalan Berhasil..");
                reset();
                kodeRawat();

            }catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {

            String kode_obat = (String) kodeObat.get((int)cbobat.getSelectedIndex());

            String sql = "UPDATE rawat_jalan SET kode_periksa='"+txtkodeperiksa.getText()+"', kode_obat='"+kode_obat+"', jumlah_obat='"+txtjmlobat.getText()+"', harga='"+txttotalharga.getText()+"' WHERE id_rawat_jalan = '"+txtkoderawat.getText()+"'";
            java.sql.Connection conn = (Connection)Koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Rawat Jalan Berhasil...");
            kodeRawat();
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        reset();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int tanya = JOptionPane.showConfirmDialog(null, "Yakin untuk menghapus data ini?","Confirmation", JOptionPane.YES_NO_OPTION);

        if(tanya==0){
            try{
                String sql = "DELETE FROM rawat_jalan WHERE id_rawat_jalan='"+txtkoderawat.getText()+"'";
                java.sql.Connection conn = (Connection)Koneksi.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Hapus Data Rawat Jalan Berhasil....");
            }catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            reset();
            kodeRawat();
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        reset();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnDataRawatJalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataRawatJalanActionPerformed
        DataRawatJalan dataRawatJalan = new DataRawatJalan();
        this.getDesktopPane().add(dataRawatJalan);
        Dimension gs = this.getDesktopPane().getSize();
        Dimension cs = dataRawatJalan.getSize();

        dataRawatJalan.setLocation((gs.width - cs.width) / 2, (gs.height - cs.height) / 2);

        dataRawatJalan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDataRawatJalanActionPerformed

    private void txtjmlobatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjmlobatKeyReleased
        if(txtjmlobat.getText().equals("") || txtjmlobat.getText().equals("0")){
            JOptionPane.showMessageDialog(rootPane, "Jumlah Obat Tidak Boleh Kosong!!!");
            txtjmlobat.setText("1");
        }else {
            int jumlahObat = Integer.parseInt(txtjmlobat.getText());
            int harga = Integer.parseInt(txtharga.getText());
            int total = harga * jumlahObat;
            txttotalharga.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_txtjmlobatKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton btnDataRawatJalan;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btncaripemeriksaan;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbobat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjmlobat;
    private javax.swing.JTextField txtkodeperiksa;
    private javax.swing.JTextField txtkoderawat;
    private javax.swing.JTextField txtnamapasien;
    private javax.swing.JTextField txttotalharga;
    // End of variables declaration//GEN-END:variables
}
